#! /bin/sh

bspc monitor LVDS1 -d 6 7 8 9 10
bspc monitor HDMI1 -d 1 2 3 4 5

bspc config border_width          2
bspc config window_gap            12
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

nitrogen --restore
