#! /bin/sh

LEFT_DESKS="$(seq 1 5)"
RIGHT_DESKS="$(seq 6 9) 0"

bspc monitor HDMI1 -d $LEFT_DESKS
bspc monitor LVDS1 -d $RIGHT_DESKS

bspc rule -a Gimp -d ^8 --follow --floating
bspc rule -a Chromium -d ^2
bspc rule -a mplayer2 --floating
bspc rule -a Kupfer.py --focus
bspc rule -a Screenkey --unmanage

bspc config split_ratio           0.52
bspc config border_width          2
bspc config window_gap            12
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

#Autoexec stuff
nitrogen --restore
